# codemagic.yaml
workflows:
  flutter-release:
    name: Flutter Release Workflow
    max_build_duration: 60  # Optional: Timeout for build in minutes

    environment:
      flutter: stable  # Using the stable version of Flutter
      # android:
      #   gradle: 6.9  # (Optional) Specify Gradle version if needed (Android)
      # xcode: latest  # Ensure that the latest version of Xcode is used for iOS builds

    scripts:
      - flutter pub get  # Install dependencies
      - flutter build apk --release  # Build release APK
      - flutter build appbundle --release  # Build AAB (for Play Store)
      - flutter build ios --release --no-codesign  # Build iOS app (without signing)
    
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk  # Save APK file
      - build/app/outputs/bundle/release/app-release.aab  # Save AAB file
      - build/ios/ipa/*.ipa  # Save IPA file

